In [2]:
import torch
import unittest
torch.set_printoptions(precision=4)
%load_ext autoreload
%autoreload 2

test = unittest.TestCase()

In [22]:
filters_per_layer=[32,64]; layers_per_block=2;
channels = [channel for channel in filters_per_layer for _ in range(layers_per_block)]

In [23]:
channels

[32, 32, 64, 64]

In [11]:
dict(negative_slope=0.02)

{'negative_slope': 0.02}

In [13]:
activation_params={'negative_slope': 0.02}

In [97]:
torch.ones((torch.randn(1, 3).shape))

tensor([[1., 1., 1.]])

In [114]:
torch.bernoulli(torch.ones((torch.randn(1, 3).shape)) * 0.4)/ 0.4

tensor([[2.5000, 0.0000, 0.0000]])

In [122]:
torch.bernoulli(torch.full(x.shape, 1-p))

tensor([[0., 0., 1.]])

In [123]:
torch.ones(x.size())*0.4

tensor([[0.4000, 0.4000, 0.4000]])

In [ ]:
        mask = torch.ones(x.size())
        if self.training_mode:
            mask = torch.bernoulli(mask * self.p) * (1 / self.p)
        self.grad_cache["mask"] = mask

In [125]:
torch.ones(x.shape)*p

tensor([[0.4000, 0.4000, 0.4000]])

x~(N,D)

In [92]:
mask = torch.ones(()
# if self.training_mode:
#         mask = torch.bernoulli(mask * self.p) * (1 / self.p)

NameError: name 'x' is not defined

In [88]:
loss = []

In [89]:
train_loss.extend(epoch_train_loss)
train_acc.append(epoch_train_acc)
test_loss.extend(epoch_test_loss)

NameError: name 'train_loss' is not defined

In [90]:
torch.normal(mean = 0, std = 0.1,size = (5,3))

tensor([[-0.0348,  0.0688, -0.0386],
        [-0.0307, -0.0849,  0.0316],
        [-0.0785, -0.0214,  0.1797],
        [-0.0188,  0.1002,  0.1016],
        [-0.0018, -0.0023,  0.1652]])

In [28]:
torch.ones(5).clone() 

tensor([1., 1., 1., 1., 1.])

In [24]:
N = 5
num_classes = 3
scores = torch.randn(N, num_classes)
labels = torch.randint(low=0, high=num_classes, size=(N,), dtype=torch.long)

In [24]:
lst =  [
    2.297480821609497,
      2.3283166885375977,
      2.2985639572143555,
      2.2980797290802,
      2.304649829864502,
      2.298022508621216,
      2.2939400672912598,
      2.3131401538848877,
      2.297905921936035,
      2.3099358081817627,
      2.290327310562134,
      2.29451584815979,
      2.2960586547851562,
      2.3086118698120117,
      2.332392930984497,
      2.310760021209717,
      2.3077354431152344,
      2.2975175380706787,
      2.296952486038208,
      2.3056766986846924,
      2.3046977519989014,
      2.292863130569458,
      2.308523654937744,
      2.3082327842712402,
      2.302281141281128,
      2.290247678756714,
      2.2797582149505615,
      2.3009538650512695,
      2.296889543533325,
      2.3175055980682373,
      2.3155295848846436,
      2.3057613372802734,
      2.285447835922241,
      2.296616792678833,
      2.2868616580963135,
      2.3095598220825195,
      2.297133207321167,
      2.275599479675293,
      2.2735767364501953,
      2.278671979904175,
      2.2796595096588135,
      2.2845401763916016,
      2.2949635982513428,
      2.2926597595214844,
      2.2967782020568848,
      2.2854559421539307,
      2.275674343109131,
      2.2954471111297607,
      2.2936179637908936,
      2.2896947860717773,
      2.272848606109619,
      2.263606071472168,
      2.251047134399414,
      2.274050235748291,
      2.2778518199920654,
      2.278243064880371,
      2.2904818058013916,
      2.2735979557037354,
      2.2776076793670654,
      2.267070770263672,
      2.2825560569763184,
      2.301093339920044,
      2.2904932498931885,
      2.2997422218322754,
      2.2570602893829346,
      2.3098745346069336,
      2.273479461669922,
      2.2752339839935303,
      2.2862002849578857,
      2.283393383026123,
      2.268204689025879,
      2.2302825450897217,
      2.2681009769439697,
      2.2639288902282715,
      2.275212049484253,
      2.299211263656616,
      2.244154453277588,
      2.290961265563965,
      2.2880284786224365,
      2.299560785293579,
      2.2769789695739746,
      2.2631726264953613,
      2.2679638862609863,
      2.267526865005493,
      2.271793842315674,
      2.260704755783081,
      2.2628068923950195,
      2.2439610958099365,
      2.255812883377075,
      2.2779183387756348,
      2.2612667083740234,
      2.262350082397461,
      2.249350070953369,
      2.259847402572632,
      2.2513935565948486,
      2.234605312347412,
      2.2780232429504395,
      2.2621567249298096,
      2.2855629920959473,
      2.264456033706665
    ]

In [27]:
len(lst)

100

In [57]:
scores[torch.arange(N),labels]

tensor([-0.6681, -1.0278,  0.8946,  1.2852,  0.2756])

In [58]:
Xy = scores[torch.arange(N),labels]

In [49]:
scores[:]

tensor([[-0.6681, -0.0795,  0.0357],
        [ 0.4357, -1.0278,  0.5812],
        [ 0.7705,  0.8946,  0.7237],
        [ 0.5962, -1.4612,  1.2852],
        [ 1.2422,  0.2756,  1.4620]])

In [43]:
scores[0::5,labels]

tensor([[-0.6681, -0.0795, -0.0795,  0.0357, -0.0795]])

In [40]:
scores[torch.arange(N),labels]

tensor([-0.6681, -1.0278,  0.8946,  1.2852,  0.2756])

In [67]:
torch.exp(scores).sum(1)

tensor([2.4726, 3.6921, 6.6693, 5.6626, 9.0950])

In [72]:
(torch.exp(scores).T / torch.exp(scores).sum(1)).T

tensor([[0.2074, 0.3735, 0.4191],
        [0.4188, 0.0969, 0.4843],
        [0.3240, 0.3668, 0.3092],
        [0.3206, 0.0410, 0.6385],
        [0.3808, 0.1448, 0.4744]])

In [66]:
(-scores[torch.arange(N),labels] + torch.log(torch.exp(scores).sum(1))).mean()

tensor(1.4582)

In [ ]:
N_range = torch.arange(N)
x_y = x[N_range, y]
log_sum = torch.log(torch.exp(x).sum(1))

### Cross-Entropy Loss

As you know by know, cross-entropy is a common loss function for classification tasks.
In class, we defined it as 

$$\ell_{\mathrm{CE}}(\vec{y},\hat{\vec{y}}) = - {\vectr{y}} \log(\hat{\vec{y}})$$

where $\hat{\vec{y}} = \mathrm{softmax}(x)$ is a probability vector (the output of softmax on the class scores $\vec{x}$) and the vector $\vec{y}$ is a 1-hot encoded class label.

However, it's tricky to compute the gradient of softmax, so instead we'll define a version of cross-entropy that produces the exact same output but works directly on the class scores $\vec{x}$.

We can write,
$$\begin{align}
\ell_{\mathrm{CE}}(\vec{y},\hat{\vec{y}}) &= - {\vectr{y}} \log(\hat{\vec{y}}) 
= - {\vectr{y}} \log\left(\mathrm{softmax}(\vec{x})\right) \\
&= - {\vectr{y}} \log\left(\frac{e^{\vec{x}}}{\sum_k e^{x_k}}\right) \\
&= - \log\left(\frac{e^{x_y}}{\sum_k e^{x_k}}\right) \\
&= - \left(\log\left(e^{x_y}\right) - \log\left(\sum_k e^{x_k}\right)\right)\\
&= - x_y + \log\left(\sum_k e^{x_k}\right)
\end{align}$$

Where the scalar $y$ is the correct class label, so $x_y$ is the correct class score.

Note that this version of cross entropy is also what's [provided](https://pytorch.org/docs/stable/nn.html#crossentropyloss) by PyTorch's `nn` module.

In [26]:
labels

tensor([0, 1, 1, 2, 1])

In [ ]:
N_range = torch.arange(N)
x_y = x[N_range, y]
log_sum = torch.log(torch.exp(x).sum(1))

self.grad_cache["x"] = x
self.grad_cache["y"] = y
return sum(log_sum - x_y) / N

1. the jacobian matrix is calculated by the all the partial derivatives of the output in respect to the input.
the input dimension is 1024, number of samples is 128 and output dimension is 2048, 
than the entire input is a tensor of shape (128, 1024) and the entire output is a tensor of shape (128, 2048).
the jacobian shape is $(128, 2048, 128, 1024)$.
when we thought of the shape it was more logical for us that the calculation is applied for each instance separatly 
and then the shape will be $(128, 2048, 1024)$. since in former way we mix derivatives between instances and most of 
the derivatives are irrelevant, but when we check in pytorch we got the result we mention before  
2. we represent each cell in our tensor in a single precision point of 4 bytes. than the the amount of memory needed in the RAM or GPU::
$$\begin{align}
\frac{(4 \cdot 128\cdot 2048 \cdot 128 \cdot 1024)} {(1024^3)} = 128 \quad gigabytes
\end{align}$$


In [79]:
from torch import autograd
# autograd.functional.jacobian()

In [113]:
 def exp_adder(x, y):
...   return 2 * x.exp() + 3 * y
inputs = (torch.rand(5,10), torch.rand(10,5))
autograd.functional.jacobian(exp_adder, inputs)[0].shape

RuntimeError: The size of tensor a (10) must match the size of tensor b (5) at non-singleton dimension 1

In [95]:
autograd.functional.jacobian(exp_adder, inputs)[0]

KeyboardInterrupt: 

In [ ]:
torch.autograd.grad(

In [100]:
import numpy as np
x = np.arange(1,3,1)
x = torch.from_numpy(x).reshape(len(x),1)
x = x.float()
x.requires_grad = True
x.shape
# w1 = torch.randn((2,2), requires_grad = True)
# y = w1@x

# # Compute gradients of w1 . x
# ... 
# y[0].backward(retain_graph=True)
# w1.grad
# y[1].backward(retain_graph=True)
# w1.grad

torch.Size([2, 1])

$(num of samples) \cdot  (num of batches) \cdot (features_{in}) \cdot (features_{out}) \cdot 4(bytes)
= 4 \cdot 128 \cdot 128 \cdot 1024 \cdot 2048 = 2^2 \cdot 2^7 \cdot 2^7 \cdot 2^{10} \cdot 2^{11} = 2^{37}
= 2^7 \cdot 2^{30} = 128 \cdot 2^{30} = ~ 128GB$

In [114]:
16+21

37

In [115]:
2**7

128

In [116]:
128**0.5

11.313708498984761

In [121]:
2**10

1024

In [127]:
import os
import numpy as np
import matplotlib.pyplot as plt
import unittest
import torch
import torchvision
import torchvision.transforms as tvtf
seed = 42
plt.rcParams.update({'font.size': 12})
test = unittest.TestCase()

In [132]:
p = torch.randn(500, 10)
dp = torch.randn(*p.shape)*2

In [135]:
p.shape

torch.Size([500, 10])

In [136]:
.view(X.shape[0], -1)

torch.Size([500, 10])

In [139]:
sd = torch.randn(10, 3,32)

In [141]:
sd.view(sd.shape[0], -1).shape

torch.Size([10, 96])

In [143]:
sd.reshape(sd.shape[0],-1).shape

torch.Size([10, 96])

In [144]:
num_correct = int((y == y_pred).sum())

NameError: name 'y_pred' is not defined

In [162]:
y = torch.randn(10)
z = torch.randn(10,30)

In [163]:
(y == y).sum().item()

10

In [164]:
z

tensor([[ 1.2419e+00,  6.2056e-01, -1.1865e+00, -6.7559e-01, -1.9728e+00,
          9.4332e-01,  1.0080e-01,  7.9020e-01,  4.4511e-01,  5.4797e-01,
         -8.7511e-02, -3.2268e-01,  3.1893e-01, -9.5148e-01,  3.2177e-01,
          6.5429e-01,  9.1643e-01, -7.5951e-01,  1.6313e+00, -5.0054e-01,
         -3.5658e+00,  9.1203e-01,  1.3815e+00, -7.3424e-02,  8.8573e-01,
          7.9249e-01, -7.5960e-01,  1.6330e+00,  9.8931e-01, -1.4648e+00],
        [-2.1900e+00,  2.7512e-01,  5.0552e-01,  9.6512e-01, -6.0260e-01,
          1.5381e-01,  9.0454e-02, -2.2326e-04, -5.6213e-01, -1.3604e-01,
          2.9462e-01,  3.3472e-01, -7.8592e-01,  2.0474e+00, -1.7926e+00,
          1.0735e-01,  1.8690e-02, -1.1196e+00,  1.0418e+00,  7.2474e-01,
         -6.1551e-01,  6.2461e-01, -5.5698e-01,  1.0178e-01,  7.3933e-02,
          1.1370e+00, -2.9739e-01,  5.3011e-01, -8.5532e-01,  1.2828e-01],
        [ 1.1826e+00,  3.5237e-01,  2.1257e+00,  1.8337e-01,  7.2058e-02,
         -3.5370e-01, -1.9184e+00,  

In [165]:
z.argmax(axis = 1)

tensor([27, 13,  2, 27,  9, 24, 27,  8,  0, 22])

In [53]:
d = None

In [54]:
d == 5

False

In [67]:
torch.stack([torch.tensor(3.1217), torch.tensor(4.8822), torch.tensor(3.2859)]).tolist()

[3.1217000484466553, 4.882199764251709, 3.285900115966797]

In [59]:
[torch.tensor(3.1217), torch.tensor(4.8822), torch.tensor(3.2859)]

AttributeError: 'list' object has no attribute 'tolist'

In [19]:
ls.extend([2,2,2,2])

TypeError: 'int' object is not iterable

In [23]:
ls + [2,2,2,2]

[1, 2, 3, 4, 2, 2, 2, 2]

In [ ]:
actual_num_epochs += 1
# train
epoch_train_loss, epoch_train_acc = self.train_epoch(dl_train, **kw)
# test
epoch_test_loss, epoch_test_acc = self.test_epoch(dl_test, **kw)
# add current results
train_loss.extend(epoch_train_loss)
train_acc.append(epoch_train_acc)
test_loss.extend(epoch_test_loss)
test_acc.append(epoch_test_acc)

In [29]:
a = torch.rand(5,5)
b = torch.rand(5,5)

In [30]:
a,b

(tensor([[0.6391, 0.4122, 0.4556, 0.8051, 0.9173],
         [0.4253, 0.7474, 0.4271, 0.7203, 0.7233],
         [0.1234, 0.1404, 0.4790, 0.2170, 0.0211],
         [0.7313, 0.9112, 0.9022, 0.9691, 0.0476],
         [0.4520, 0.2382, 0.5294, 0.2002, 0.3769]]),
 tensor([[0.9212, 0.4681, 0.9489, 0.5220, 0.3115],
         [0.0206, 0.5518, 0.6165, 0.8729, 0.1746],
         [0.9841, 0.5628, 0.3618, 0.0521, 0.5666],
         [0.3705, 0.5983, 0.7771, 0.2047, 0.4351],
         [0.8235, 0.9699, 0.5412, 0.5907, 0.0707]]))

In [35]:
a.te

tensor([[0.6391, 0.4122, 0.4556, 0.8051, 0.9173],
        [0.4253, 0.7474, 0.4271, 0.7203, 0.7233],
        [0.1234, 0.1404, 0.4790, 0.2170, 0.0211],
        [0.7313, 0.9112, 0.9022, 0.9691, 0.0476],
        [0.4520, 0.2382, 0.5294, 0.2002, 0.3769]])

In [38]:
torch.stack(torch.rand(5))

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [40]:
torch.mean(torch.stack((a,a)))

tensor(0.5045)

In [45]:
torch.stack((a,a)).mean()

tensor(0.5045)

In [48]:
a.mean(),b.mean()

(tensor(0.5045), tensor(0.5327))

In [49]:
a

tensor([[0.6391, 0.4122, 0.4556, 0.8051, 0.9173],
        [0.4253, 0.7474, 0.4271, 0.7203, 0.7233],
        [0.1234, 0.1404, 0.4790, 0.2170, 0.0211],
        [0.7313, 0.9112, 0.9022, 0.9691, 0.0476],
        [0.4520, 0.2382, 0.5294, 0.2002, 0.3769]])

In [52]:
a.mean().item() > None

TypeError: '>' not supported between instances of 'float' and 'NoneType'

In [69]:
[torch.zeros(size=(1,))] * 5

[tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.])]

In [74]:
[torch.zeros(1)]*5

[tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.])]

In [80]:
l = [1,2,3,45]

In [84]:
l.index

ValueError: 0 is not in list